### ISSUE TITLE
[resolve] streamlink plugin requests that would work with resolve.py

### ISSUE THREAD

**Issue by back-to** [back-to/plugins#1]
## resolve.py

Streamlink Plugin that will try to find a validate streamurl

For more informations read
https://github.com/back-to/plugins/blob/master/README.md#resolvepy

---

- **github url**
https://github.com/back-to/plugins/blob/master/plugins/resolve.py
- **raw file**
https://raw.githubusercontent.com/back-to/plugins/master/plugins/resolve.py

### Plugin requests

- https://github.com/streamlink/streamlink/issues/506
- https://github.com/streamlink/streamlink/issues/846
- https://github.com/streamlink/streamlink/issues/979
  some playlists have to many urls, you can get all urls with `-l debug`
- https://github.com/streamlink/streamlink/issues/1165
`  resolve://URL best --http-no-ssl-verify` for sportal
- https://github.com/streamlink/streamlink/issues/1207
- https://github.com/streamlink/streamlink/issues/1226
- https://github.com/streamlink/streamlink/issues/1320
- https://github.com/streamlink/streamlink/issues/1385

**Comment by karlo2105** [comment]
@back-to 
Thanks very much it works great on sites I tested. Could you add this website ?
`http://ustreamyx.com/`

**Comment by back-to** [comment]
it would not work with this plugin `resolve.py`

i don't have an interest for the website, so no.

**Comment by karlo2105** [comment]
What about a support for this : `http://stadium.dinozap.info/` ?

**Comment by ls117** [comment]
Can we work out something for a fix on camsoda? Not the current one because that was not what I was looking for. I'd prefer we talk via email because this doesn't need to be public

**Comment by johnthecracker** [comment]
@back-to 

what is the obstacle of supporting rtmp?

technical or ethical?

**Comment by johnthecracker** [comment]
@ls117 

plugin is very public.

**Comment by back-to** [comment]
@johnthecracker 
because most of the time there is a m3u8 link next to the rtmp link,
so i just grab it.

i don't really have good example websites where there are only rtmp links without an api, behind a .js file or weird params

**Comment by johnthecracker** [comment]
The reason I ask is because there are not many rtmp streams around and not much enthusiasm for development.

However, somebody may be interested in rtmp functionality for the sake of himself and contribute to plugin.

Wherever there are rtmp and hls streams side by side, they are never of the same quality.

Most of times I see rtmp stream clearer than hls stream in a player.

Just having ability to get hold of rtmp url comes good sometimes.

**Comment by ls117** [comment]
@johnthecracker i wasn't asking for a public fix, something private would be best.

**Comment by johnthecracker** [comment]
On stream-recorder forum it is possible for members to send private messages to one another (PM).
Now you contact me in a similar way here.

**Comment by johnthecracker** [comment]
These developers need private circle to share porn? Who knows.

**Comment by ls117** [comment]
I send you a pm on the forum @johnthecracker
