### ISSUE TITLE
use with proxy

### ISSUE THREAD

**Issue by e2pluginss** [back-to/plugins#1]
can liveproxy be use with a proxy?

**Comment by back-to** [comment]
if you mean **http / https / socks** proxy most likely yes

https://streamlink.github.io/cli.html#proxy-support
https://streamlink.github.io/cli.html#cmdoption-http-proxy

**but I did not test it.**

You just need to create a valid url with it

https://liveproxy.github.io/url.html#options

---

if you mean something else please explain it
