### ISSUE TITLE
ok_ru module not working

### ISSUE THREAD

**Issue by torrdek** [back-to/plugins#11]
hi:-)

'from streamlink.compat import html_unescape, unquote'   is failing, because'html_unescape' is not found in 'streamlink.compat' any more.
Thank you for your hard work, and I hope you can fix it
T

**Comment by back-to** [comment]
@torrdek 
your **streamlink** version is **to old**,
you will need to install the `Streamlink Development version`

https://github.com/back-to/plugins#how-can-i-use-the-streamlink-development-version

**Comment by torrdek** [comment]
Oh ok...I was using the last version...Will get the developer version then. Thanks for your quick answer...

Sent from Yahoo Mail on Android 
 
  On Mon, Aug 13, 2018 at 13:08, back-to<notifications@github.com> wrote:   
@torrdek
your streamlink version is to old,
you will need to install the Streamlink Development version

https://github.com/back-to/plugins#how-can-i-use-the-streamlink-development-version
