### ISSUE TITLE
Neulion?

### ISSUE THREAD

**Issue by ryanjgillies** [back-to/plugins#13]
Hi @back-to - you made quite a few commits to the streamlink plugin that dealt with neulion streams so I thought I'd take a shot at raising it here.

Understandably the developers there don't want to deal with the hassle that comes with the takedown notice, but I wondered if there was any chance you would be interested in maintaining it in your plugins repo instead (where it might not get picked up so easily)...?

Not having access to ElevenSports is killing me - streamlink was a godsend for running the streams in a far less bloated manner on my machine.  Anything you could do (if willing) to bring the plugin up to date would be endlessly appreciated!

**Comment by back-to** [comment]
No interest.
