### ISSUE TITLE
Help, issue installing

### ISSUE THREAD

**Issue by longsack** [back-to/plugins#8]
I get the following error when trying to install....

root@ns3923:/var/www/clients/plugins# ln -s "$(pwd)/plugins/" "$HOME/.config/streamlink/"
ln: target ‘/root/.config/streamlink/’ is not a directory: No such file or directory

Not sure where else to look for the streamlink plugins?  Any idea what i'm doing wrong?

Debian 8
sudo pip install streamlink

**Comment by back-to** [comment]
you need to create the default config folder for streamlink

`mkdir $HOME/.config/streamlink`
